#!/bin/sh
# build.sh — run by Vercel before serving
# Injects SUPABASE_URL and SUPABASE_ANON_KEY environment variables
# into config.js so the browser can access them without exposing
# them in your Git repository.
#
# Set these in Vercel → Project → Settings → Environment Variables.

cat > config.js << EOF
/* Generated by build.sh — do not edit manually */
window.SUPABASE_URL      = '${SUPABASE_URL}';
window.SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
EOF

echo "[uni-co build] config.js written from environment variables."
